package sk.stefan.MVP.view.components;

import com.vaadin.data.util.TextFileProperty;
import com.vaadin.ui.RichTextArea;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.VerticalLayout;

public class TBD_KomB2 extends VerticalLayout {//CustomComponent {

    /**
     *
     */
    private static final long serialVersionUID = 1483207822865496626L;

    private VerticalLayout mainLayout;

    private TabSheet tabSheet_1;

    private TextArea HTML;

    private RichTextArea TEXT;

    /**
     * The constructor should first build the main layout, set the composition
     * root and then do any custom initialization.
     *
     * The constructor will not be automatically regenerated by the visual
     * editor.
     */
    public TBD_KomB2() {

        this.addComponent(buildMainLayout());
		//buildMainLayout();
        // TODO add user code here
    }

    public void setPropertyDataSource(TextFileProperty doc) {

        TEXT.setPropertyDataSource(doc);
        HTML.setPropertyDataSource(doc);

    }

    //@AutoGenerated
    private VerticalLayout buildMainLayout() {

        // common part: create layout
        mainLayout = new VerticalLayout();
        mainLayout.setImmediate(false);
        mainLayout.setSizeFull();

        // tabSheet_1
        tabSheet_1 = buildTabSheet_1();
        tabSheet_1.setSizeFull();
        mainLayout.addComponent(tabSheet_1);

        return mainLayout;
    }

    //@AutoGenerated
    private TabSheet buildTabSheet_1() {
        // common part: create layout
        tabSheet_1 = new TabSheet();
        tabSheet_1.setImmediate(true);

        // TEXT
        TEXT = new RichTextArea();
        TEXT.setImmediate(false);
        TEXT.setSizeFull();
        tabSheet_1.addTab(TEXT, "TEXTa", null);

        // HTML
        HTML = new TextArea();
        HTML.setImmediate(false);
        HTML.setSizeFull();
        tabSheet_1.addTab(HTML, "HTMLa", null);

        return tabSheet_1;
    }

}
