DROP TABLE IF EXISTS `addressbook_1`;
CREATE TABLE `addressbook_1` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(50) DEFAULT NULL,
  `LAST_NAME` varchar(50) DEFAULT NULL,
  `COMPANY` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO `addressbook_1` (`ID`, `FIRST_NAME`, `LAST_NAME`, `COMPANY`) VALUES
(1000,	'Stefan',	'Veres',	'PE Lynch'),
(1001,	'Frigo',	'Torac',	'Oracle'),
(1002,	'Tonik',	'Kapusta',	'Tesla Stropkovt'),
(1003,	'Tonik',	'Lopatka',	'Oracle'),
(1004,	'Maria',	'Veres',	'CB&I'),
(1005,	'Peter',	'Sarkoci',	'Della Roma'),
(1006,	'Arana',	'GenoVA',	'Istrochem'),
(1007,	'Arana',	'Berki',	'Slovnaft'),
(1008,	'Frigo',	'Olah',	'Tesla Stropkov'),
(1009,	'Peter',	'Sarkoci',	'Slovakofarma Hlohove'),
(1010,	'AranaC',	'Torac',	'JZD Slusovice Rahoj'),
(1011,	'Pistik',	'Puskaro',	'Slovakofarma Hlohovec'),
(1012,	'ARANKA',	'MAuaMová',	'SlovnaftHHH'),
(1013,	'Mária',	'Mošašová',	'Istrochem a.s'),
(1014,	'Gejza',	'Vransky',	'JZD Slusovice'),
(1015,	'Koloman',	'Veres',	'Tesla StropkovWAW'),
(1016,	'Rene',	'Geno',	'DellON'),
(1017,	'Frigo',	'LakatosIKCKO',	'IBM'),
(1018,	'Gejza Kalman',	'Mosat',	'Tesla Stropkov'),
(1019,	'Koloman',	'SiposKO',	'Slovnaft'),
(1020,	'Arana',	'Geno',	'IstrochemKO'),
(1021,	'Pistik',	'Puska',	'Oracle'),
(1022,	'Gejza',	'Sipos',	'Dell KOMOS'),
(1023,	'Pistik',	'Kapusta',	'CB&I'),
(1024,	'Frigo',	'Berki',	'IBM'),
(1025,	'Stefan',	'Olah',	'JZD Slusovice'),
(1026,	'Peter',	'Vransky',	'IBM'),
(1027,	'Arana',	'Vransky',	'IBM'),
(1028,	'Arana',	'Olah',	'Oracle'),
(1029,	'Dezider',	'Mosat',	'CB&I'),
(1030,	'Pistik',	'Lakatos',	'Dell'),
(1031,	'Pavol',	'Curka',	'JZD Slusovice'),
(1032,	'Arana',	'SarkociOVA',	'JZD Slusovice KAmzík'),
(1033,	'Rene',	'Geno',	'Slovakofarma Hlohovec'),
(1034,	'Gejza',	'Geno',	'Slovakofarma Hlohovec'),
(1035,	'Michal',	'Cibula',	'JZD Slusovice'),
(1036,	'Gejza',	'Murko',	'Istrochem'),
(1037,	'Peter',	'Puska',	'IBM'),
(1038,	'Stefan',	'Tehla',	'CB&I'),
(1039,	'Gejza',	'Lakatos',	'Slovakofarma Hlohovec'),
(1040,	'Andrej',	'Olah',	'Slovnaft'),
(1041,	'Maria',	'Kapusta',	'CB&I'),
(1042,	'Rene',	'Vransky',	'CB&I'),
(1043,	'Dezider',	'Lakatos',	'Slovnaft'),
(1044,	'Stefan',	'Berki',	'Istrochem'),
(1045,	'Maria',	'Murko',	'Slovakofarma Hlohovec'),
(1046,	'Koloman',	'Mosat',	'Slovakofarma Hlohovec'),
(1047,	'Rene',	'Lakatos',	'Dell'),
(1048,	'Frigo',	'Veres',	'Oracle'),
(1049,	'Gejza',	'Torac',	'Tesla Stropkov'),
(1050,	'Andrej',	'Kapusta',	'Slovnaft'),
(1051,	'Dezider',	'Sipos',	'Slovnaft'),
(1052,	'Pavol',	'Torac',	'Dell'),
(1053,	'Dezider',	'Puska',	'Dell'),
(1054,	'Maria',	'Lakatos',	'JZD Slusovice'),
(1055,	'Pavol',	'Lopata',	'Tesla Stropkov'),
(1056,	'Tonik',	'Tehla',	'Tesla Stropkov'),
(1057,	'Maria',	'MosatOVA kobzova',	'Istrochem'),
(1058,	'Peter',	'Kapusta',	'Oracle'),
(1059,	'Stefan',	'Veres',	'JZD Slusovice'),
(1060,	'Gejza',	'Vransky',	'CB&I'),
(1061,	'Pistik',	'Geno',	'Tesla Stropkov'),
(1062,	'Pavol',	'Cibula',	'Slovnaft'),
(1063,	'Tonik',	'Curka',	'Istrochem'),
(1064,	'Michal',	'Geno',	'Tesla Stropkov'),
(1065,	'Stefan',	'Sipos',	'Slovnaft'),
(1066,	'Pistik',	'Geno',	'Slovnaft'),
(1067,	'Rene',	'Sipos',	'Slovakofarma Hlohovec'),
(1068,	'Pistik',	'Lopata',	'Dell'),
(1069,	'Maria',	'Berki',	'Slovnaft'),
(1070,	'Dezider',	'Lopata',	'CB&I'),
(1071,	'Peter',	'Sipos',	'Oracle'),
(1072,	'Pavol',	'Murko',	'JZD Slusovice'),
(1073,	'Michal',	'Vransky',	'Slovnaft'),
(1074,	'Andrej',	'Mosat',	'Slovakofarma Hlohovec'),
(1075,	'Rene',	'Cibula',	'Oracle'),
(1076,	'KAMILA',	'Torac',	'Istrochem'),
(1077,	'Pavol',	'Curka',	'Oracle'),
(1078,	'Rene',	'Torac',	'CB&I'),
(1079,	'Stefan',	'Cibula',	'Slovnaft'),
(1080,	'Rene',	'Puska',	'Dell'),
(1081,	'Maria',	'Tehla',	'IBM'),
(1082,	'Michal',	'Berki',	'Slovakofarma Hlohovec'),
(1083,	'Koloman',	'Geno',	'Slovakofarma Hlohovec'),
(1084,	'Koloman',	'Kapusta',	'Dell'),
(1085,	'Peter',	'Sipos',	'Dell'),
(1086,	'Peter',	'Murko',	'Slovakofarma Hlohovec'),
(1087,	'Michal',	'Sipos',	'Tesla Stropkov'),
(1088,	'Peter',	'Torac',	'Dell'),
(1089,	'Arana',	'Veres',	'Slovnaft'),
(1090,	'Rene',	'Murko',	'Istrochem'),
(1091,	'Rene',	'Lakatos',	'Oracle'),
(1092,	'Pistik',	'Olah',	'Slovakofarma Hlohovec'),
(1093,	'Pavol',	'Sarkoci',	'Slovnaft'),
(1094,	'Rene',	'Torac',	'Istrochem'),
(1095,	'Rene',	'Cibula',	'CB&I'),
(1096,	'Dezider',	'Sarkoci',	'Istrochem'),
(1097,	'Andrej',	'Kapusta',	'Tesla Stropkov'),
(1098,	'Rene',	'Lakatos',	'Istrochem'),
(1099,	'Pavol',	'Veres',	'JZD Slusovice'),
(1100,	'Arana',	'Olah',	'JZD Slusovice'),
(1101,	'Arana',	'Tehla',	'Slovakofarma Hlohovec'),
(1102,	'Gejza',	'Sarkoci',	'Tesla Stropkov'),
(1103,	'Tonik',	'Veres',	'IBM'),
(1104,	'Pistik',	'Sarkoci',	'Tesla Stropkov'),
(1105,	'Koloman',	'Kapusta',	'Slovakofarma Hlohovec'),
(1106,	'Andrej',	'Lakatos',	'Istrochem'),
(1107,	'Tonik',	'Geno',	'Istrochem'),
(1108,	'MariaNA',	'Curkova',	'Istrochem'),
(1109,	'Karol',	'Stieranka',	'STAVEL s.r.o'),
(1110,	'Tonko',	'Toman',	'FLOR'),
(1111,	'Lukas',	'Janacek',	'Syntea'),
(1112,	'Karolko',	'Maly',	'Syntea'),
(1113,	'Johan',	'Velky',	'Syntea'),
(1114,	'Stefan',	'Veres',	'Atman'),
(1115,	'Karol',	'Maray',	'CBI'),
(1116,	'Ferko',	'Malina',	'Epron'),
(1117,	'Kamil',	'Malinky',	'Stropkov'),
(1118,	'Suzi',	'kvatro',	'quills'),
(1119,	'Karol',	'Konarik',	'Bystricar'),
(1120,	'dsfdsfdsfd',	'Contact',	'dsfdsfds'),
(1121,	'KAMIL',	'SEBES',	'CBI'),
(1122,	'Karol',	'Contact',	'PE LYNCH');