package sk.stefan.MVP.view.superseded;

import sk.stefan.MVP.view.components.NavigationComponent;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.Navigator;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.MenuBar;
import com.vaadin.ui.TabSheet;
import com.vaadin.ui.VerticalLayout;

public class Kos8View extends VerticalLayout implements View {

    /*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
    private AbsoluteLayout mainLayout;
    private TabSheet tabSheet_1;
    private MenuBar menuBar_2;

    public Kos8View(Navigator nav) {

        this.buildMainLayout();
        this.addComponent(mainLayout);
        this.addComponent(NavigationComponent.getNavComp());
    }

    private AbsoluteLayout buildMainLayout() {
        // common part: create layout
        mainLayout = new AbsoluteLayout();
        mainLayout.setImmediate(false);
        mainLayout.setWidth("100%");
        mainLayout.setHeight("100%");

        // top-level component properties
        setWidth("100.0%");
        setHeight("100.0%");

        // tabSheet_1
        tabSheet_1 = buildTabSheet_1();
        mainLayout.addComponent(tabSheet_1, "top:0.0px;left:0.0px;");

        return mainLayout;
    }

    @AutoGenerated
    private TabSheet buildTabSheet_1() {
        // common part: create layout
        tabSheet_1 = new TabSheet();
        tabSheet_1.setImmediate(true);
        tabSheet_1.setWidth("100.0%");
        tabSheet_1.setHeight("100.0%");

        // menuBar_2
        menuBar_2 = new MenuBar();
        menuBar_2.setImmediate(false);
        menuBar_2.setWidth("100.0%");
        menuBar_2.setHeight("-1px");
        tabSheet_1.addTab(menuBar_2, "Tab", null);

        return tabSheet_1;
    }

    @Override
    public void enter(ViewChangeEvent event) {
		// TODO Auto-generated method stub

    }

}
